---
- hosts: all
  tasks:
    - name: Import Compute Node Role
      import_role:
        name: compute_node
      tags:
        - compute
        - never
    - name: Import Node Prep Role
      import_role:
        name: node_prep
      tags:
        - compute
        - login
    - name: Import Login Node Role
      import_role:
        name: login_node
      tags:
        - login
        - never