---
- hosts: all
  tasks:
    - name: Import Node Prep Role
      import_role:
        name: node_prep
      tags:
        - login
        - compute
        - storage
        - slurm
    - name: Import Compute Node Role
      when: inventory_hostname in groups['compute_nodes']
      import_role:
        name: compute_node
      tags:
        - compute
        - never
    - name: Import Login Node Role
      when: inventory_hostname in groups['login_nodes']
      import_role:
        name: login_node
      tags:
        - login
        - never
    - name: Import Storage Node Role
      when: inventory_hostname in groups['storage_nodes']
      import_role:
        name: storage_node
      tags:
        - storage
        - never
    - name: Import Slurm Node Role
      when: inventory_hostname in groups['slurm_nodes']
      import_role:
        name: slurm_node
      tags:
        - slurm
        - never