#!/bin/bash
# generate 125 cases
~jason/.local/bin/parallel -kj2 echo 1e{1} {2}e-1 {3}e-2 50 ::: $(seq 1 5) ::: $(seq 5 9) ::: $(seq 1 5) > cases/cases-to-run
# also generate log directory
mkdir log/
