  - name: set hostname
    command: hostnamectl set-hostname {{storage_name}}
    ignore_errors: yes
  
  - name: make sure scratch exists
    file:
      path: /scratch
      state: directory
  
  - name: make sure packages exists
    file:
      path: /packages
      state: directory

  - name: make sure packages exists
    file:
      path: /home
      state: directory
      
  - name: enable nfs exports
    lineinfile: dest=/etc/exports line="/packages *(rw,sync,no_subtree_check,no_root_squash)"
  
  - name: enable nfs exports
    lineinfile: dest=/etc/exports line="/scratch *(rw,sync,no_subtree_check,no_root_squash)"

  - name: enable nfs exports
    lineinfile: dest=/etc/exports line="/home *(rw,sync,no_subtree_check,no_root_squash)"
    
  - name: export nfs
    command: exportfs -a

  - name: restart nfs
    command: service nfs restart
    
  - name: enable nfs
    command: systemctl enable nfs
