########## CONFIGURE DNS ##########

  - name: check host file for correct resolv.conf
    lineinfile: dest=/etc/resolv.conf line="nameserver 8.8.8.8"

  - name: restart networking
    command: service network restart

################ HOSTS #####################

  - name: check host file for correct hosts
    lineinfile: dest=/etc/hosts line="{{login_ip}}        {{login_name}}"
  - name: check host file for correct hosts
    lineinfile: dest=/etc/hosts line="{{compute1_ip}}        {{compute1_name}}"
  - name: check host file for correct hosts
    lineinfile: dest=/etc/hosts line="{{compute2_ip}}        {{compute2_name}}"
  - name: check host file for correct hosts
    lineinfile: dest=/etc/hosts line="{{compute3_ip}}        {{compute3_name}}"
  - name: check host file for correct hosts
    lineinfile: dest=/etc/hosts line="{{compute4_ip}}        {{compute4_name}}"

########## INSTALL PACKAGES ##########

  - name: clear cache
    command: yum clean all

  - name: install epel
    yum:
      name: ['epel-release']
      update_cache: yes
      state: present

  - name: install development tools
    yum:
      name: ['@development tools']
      update_cache: yes
      state: present
      
  - name: install packages
    yum:
      name: ['wget', 'parallel']
      update_cache: yes
      state: present


########## DISABLE SELINUX ##########

  - selinux:
      state: disabled
