########## CONFIGURE DNS ##########

  - name: check host file for correct resolv.conf
    lineinfile: dest=/etc/resolv.conf line="nameserver 1.1.1.1"

  - name: restart networking
    command: service network restart

########## INSTALL PACKAGES ##########

  - name: clear cache
    command: yum clean all

  - name: install epel
    yum:
      name: ['epel-release']
      update_cache: yes
      state: present

  - name: install development tools
    yum:
      name: ['@development tools']
      update_cache: yes
      state: present
      
  - name: install wget
    yum:
      name: ['wget']
      update_cache: yes
      state: present

  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest

########## DISABLE SELINUX ##########

  - selinux:
      state: disabled
      
########## ADD USERS ###########

   - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
     ansible.builtin.user:
      name: john
      password: tbQ2Qsmk
      comment: Johnathan
      uid: 1999
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

   - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
     ansible.builtin.user:
      name: jason
      password: tbQ2Qsmk
      comment: Jason
      uid: 2000
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      
   - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
     ansible.builtin.user:
      name: will
      password: tbQ2Qsmk
      comment: William
      uid: 2001
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
