########## CONFIGURE DNS ##########

  - name: check host file for correct resolv.conf
    lineinfile: dest=/etc/resolv.conf line="nameserver 8.8.8.8"

  - name: restart networking
    command: service network restart

########## INSTALL PACKAGES ##########

  - name: clear cache
    command: yum clean all

  - name: install epel
    yum:
      name: ['epel-release']
      update_cache: yes
      state: present

  - name: install development tools
    yum:
      name: ['@development tools']
      update_cache: yes
      state: present
      
  - name: install wget
    yum:
      name: ['wget']
      update_cache: yes
      state: present

  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest

########## DISABLE SELINUX ##########

  - selinux:
      state: disabled
