########## CONFIGURE DNS ##########

  - name: check host file for correct resolv.conf
    lineinfile: dest=/etc/resolv.conf line="nameserver 1.1.1.1"

  - name: restart networking
    command: service network restart

########## INSTALL PACKAGES ##########

  - name: install epel
    yum:
      name: ['epel-release']
      update_cache: yes
      state: present

  - name: install development tools
    yum:
      name: ['@development tools']
      update_cache: yes
      state: present

  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest

########## DISABLE SELINUX ##########

  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled